# Generated by Django 4.0.3 on 2022-05-02 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0013_lasthesab'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='status',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default='no', max_length=100),
        ),
        migrations.AlterField(
            model_name='hesab',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekhesab', to='hesab.week'),
        ),
        migrations.AlterField(
            model_name='lasthesab',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weeklasthesab', to='hesab.week'),
        ),
        migrations.AlterField(
            model_name='mainhesab',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekmainhesab', to='hesab.week'),
        ),
        migrations.AlterField(
            model_name='shopping',
            name='week',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekshopping', to='hesab.week'),
        ),
    ]
