# Generated by Django 4.0.3 on 2022-05-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0014_week_status_alter_hesab_week_alter_lasthesab_week_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hesab',
            old_name='amount',
            new_name='money',
        ),
    ]
