# Generated by Django 4.0.3 on 2022-05-02 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hesab', '0015_rename_amount_hesab_money'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hesab',
            name='money',
        ),
        migrations.RemoveField(
            model_name='hesab',
            name='negative',
        ),
        migrations.RemoveField(
            model_name='hesab',
            name='plus',
        ),
        migrations.RemoveField(
            model_name='hesab',
            name='week',
        ),
    ]
